export { LoginPage } from './LoginPage'
export { DashboardPage } from './DashboardPage'
export { TablePage } from './TablePage'
export { FormPage } from './FormPage'
export { ForgotPasswordPage } from './ForgotPasswordPage'
